### ISSUE TITLE
different URDF initial position 

### ISSUE THREAD

**Issue by HM102** [rerun-io/python-example-droid-dataset#6]
Hello,

I have data in RLDS format as well, I can visualize everything and code works. However, visualizing the robot URDF is incorrect. I think you are transforming based on initial joint position of driod franka robot, since I have different joint initial position, the transformation is incorrect. 

How can I modify the panda.urdf to match my initial position?

**Comment by 02alexander** [comment]
You could set different start transformation by modifying the `rpy` property in every  `<origin>` element for each joint, for example 
```xml
<joint name="panda_joint2" type="revolute">
    <!-- <origin rpy="-1.5707963267948966 0 0" xyz="0 0 0"/> Unmodified origin -->
    <origin rpy="-1.5707963267948966 0.8 0" xyz="0 0 0"/> <!-- Changes start angle by 0.8 radians -->
```
But I think it can get a bit tricky to figure out which axis to orient so I created a [branch](https://github.com/rerun-io/python-example-droid-dataset/tree/alexander/joint-offset) where you can set the offsets via a command line argument like this:
```bash
src/rlds.py --data data/1.0.0/ --joint-offsets "1.5, 0.0, 0, 0, 0, 0"
```
Please tell me this solves your issue.

**Comment by HM102** [comment]
Yes works. thank you.
