### ISSUE TITLE
I try to extract the 2D position of the gripper in the videos with camera extrinsics and intrinsics, but get some errors

### ISSUE THREAD

**Issue by StarCycle** [rerun-io/python-example-droid-dataset#9]
Hello @Wumpf @02alexander:

I try to extract the 2D position of the gripper in the Droid videos with camera extrinsics and intrinsics. The code is:

```
import numpy as np
import cv2
import torch

# I read the intrinsics from a svo file
# There are some small differences among the 3rd person cameras, but reading the specific intrinsic of specific camera does not improve the result
FOCAL_LEN = 531.72650146
CX = 636.15197754
CY = 344.00894165
RESOLUTION_SCALE_DOWN = 4
additional_row = np.array([0, 0, 0, 1]).reshape(1, 4)

def project(world_traj, rot, trans):
    # Get extrinsics matrix from rotation and translation
    extrinsics = np.concatenate([rot, trans.reshape(3, 1)], axis=1)
    T_world_cam = np.concatenate([extrinsics, additional_row], axis=0)

    # Get 3D traj in camera frame
    ones = np.ones((world_traj.shape[0], 1))
    world_traj = np.concatenate([world_traj, ones], axis=1)
    camera_traj = (T_world_cam @ world_traj.T)[:3]
    x = camera_traj[0]
    y = camera_traj[1]
    z = camera_traj[2]

    # Get pixel traj
    pix_u = x * FOCAL_LEN / z + CX
    pix_v = y * FOCAL_LEN / z + CY
    pixel_traj = np.stack([pix_u, pix_v], axis=1) / RESOLUTION_SCALE_DOWN
    pixel_traj = pixel_traj.astype(np.int32)

    return pixel_traj

if __name__ == "__main__":
    extrinsic_6d, world_traj = ... # read from the dataset
    rot = Rotation.from_euler("xyz", np.array(extrinsic_6d[3:])).as_matrix()
    trans = extrinsic_6d[:3]
    pixel_traj = project(world_traj, rot, trans)
    
    # visualize the 2d trajectories with visualization class of co-tracker (do not use the tracking model)
    video = ... # read from dataset
    vis = Visualizer(save_dir="./track_result", pad_value=0, linewidth=5, tracks_leave_trace=-1)
    pixel_traj = torch.from_numpy(pixel_traj).view(1, -1, 1, 2)
    vis.visualize(video, pixel_traj)
```

However, it still cannot extract 2d position of the gripper correctly. With the same code I can get 2d position from CALVIN/Robosuite, but not Droid...Is my code wrong or the extrinsics are not well calibrated? Do you have any recommendation to debug it?

A mirror issue is: https://github.com/droid-dataset/droid/issues/39

**Comment by 02alexander** [comment]
I think the issue in your code is that you assume the extrinsics from DROID describe the world-to-camera coordinates transformation, but in fact they describe the opposite,  the camera-to-world transformation.  So you have to inverse the transformation before applying it to the gripper position.
I tried to project the gripper position myself and this works when inserted into src/raw.py line 320:
```py
gripper_cartesian_pos = self.trajectory['action']['robot_state']['cartesian_position'][i][:3]
test_cam_name = "ext1"

cam = self.cameras[test_cam_name]
extrinsics_left = self.trajectory["observation"]["camera_extrinsics"][
    f"{self.serial[test_cam_name]}_left"
][i]

rotation = Rotation.from_euler(
    "xyz", np.array(extrinsics_left[3:])
).as_matrix()
translation = extrinsics_left[:3]

# Defines the camera- to world affine transformation for homogenous coordinates
cam_to_world = np.zeros((4,4))
cam_to_world[:3,:3] = rotation
cam_to_world[:3, 3] = translation
cam_to_world[3,3] = 1

# Get the world to camera transformation
world_to_cam = np.linalg.inv(cam_to_world)

cam3dcords = (world_to_cam @ np.concatenate([gripper_cartesian_pos, [1]]))[:3]

"""
cam.left_intrinsic_mat = [
    [522.42260742   0.         653.9631958 ]
    [  0.         522.42260742 358.79196167]
    [  0.           0.           1.        ]
]
"""
proj_hom = cam.left_intrinsic_mat @ cam3dcords
proj = (proj_hom / proj_hom[2])[:2]

rr.log('/cameras/ext1/left/gripper_pos', rr.Points2D([proj], radii=20))            
```
The resulting visualization is shown below.
Does this solve your issue?

https://github.com/user-attachments/assets/d8df478b-55a8-4357-aabe-82378fee3b1b

**Comment by StarCycle** [comment]
@02alexander 

Great thanks and you definitely save my project! You are my hero!

In fact I can use an "average" camera intrinsics for the 2 external camera:

```
cam.left_intrinsic_mat = [
    [520., 0.,  640],
    [  0,  520, 360],
    [  0,    0.     1. ],
]
```

Then I can avoid reading the svo files...now I only use the RLDS dataset videos and the metadata json file to get the following result:

https://github.com/user-attachments/assets/47765de3-a916-4834-92ac-0c62f362a9f0

**Comment by Hyperwjf** [comment]
> [@02alexander](https://github.com/02alexander)
> 
> Great thanks and you definitely save my project! You are my hero!
> 
> In fact I can use an "average" camera intrinsics for the 2 external camera:
> 
> ```
> cam.left_intrinsic_mat = [
>     [520., 0.,  640],
>     [  0,  520, 360],
>     [  0,    0.     1. ],
> ]
> ```
> 
> Then I can avoid reading the svo files...now I only use the RLDS dataset videos and the metadata json file to get the following result:
> 
>  video.mp4

It really works. Thanks a lot!
